# Change these first
owner: devteam156 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: YT-Music
    url: https://YT-Music.developerteam2.repl.co
  - name: MC Server
    check: "tcp-ping"
    url: 65.108.199.248
    port: 19620
  

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: devteam156.github.io/upptime/
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Statuspage
  introTitle: "This page monitoring status of pages and projects."
  introMessage: Only monitoring site.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
